AWSTemplateFormatVersion: "2010-09-09"
Mappings:
  RegionMap:
    us-east-1:
      ami: ami-0ff8a91507f77f867
    ap-south-1:
      ami: ami-08569b978cc4dfa10
Resources: 
  myEC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", ami]
      InstanceType: m1.small 